import {parseHTML} from 'linkedom';
import assert from 'node:assert/strict';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {build} from 'esbuild';
const db=new DatabaseSync(':memory:');
for(const file of ['0000_faithful_giant_man.sql','0001_dapper_baron_zemo.sql','0002_plain_masque.sql','0003_busy_colonel_america.sql'])db.exec(readFileSync('drizzle/'+file,'utf8').replaceAll('--> statement-breakpoint',''));
globalThis.testDB=db;globalThis.chatCalls=0;
mkdirSync('.test-build',{recursive:true});
writeFileSync('.test-build/runtime.ts',`const db=(globalThis as any).testDB; class Statement{args:any[]=[];constructor(public sql:string){}bind(...args:any[]){const s=new Statement(this.sql);s.args=args;return s}async first(){return db.prepare(this.sql).get(...this.args)||null}async run(){return {meta:{changes:Number(db.prepare(this.sql).run(...this.args).changes)}}}}export const env={GROQ_API_KEY:'test-key',STUDIO_USERNAME:'test-owner',STUDIO_PASSWORD:'test-owner-password',DB:{prepare:(s:string)=>new Statement(s),async batch(statements:Statement[]){db.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());db.exec('COMMIT');return results}catch(e){db.exec('ROLLBACK');throw e}}}};export const database=()=>({execute:async()=>({})});`);
await build({entryPoints:['api/index.ts'],outfile:'.test-build/handler.mjs',bundle:true,platform:'node',format:'esm',packages:'external',plugins:[{name:'test-db',setup(b){b.onResolve({filter:/lib\/runtime|\.\/runtime/},()=>({path:new URL('../.test-build/runtime.ts',import.meta.url).pathname}))}}]});
const handler=(await import('../.test-build/handler.mjs')).default;
const originalFetch=globalThis.fetch;globalThis.fetch=async(url,options)=>{assert.equal(url,'https://api.groq.com/openai/v1/chat/completions');globalThis.chatCalls++;return Response.json({choices:[{message:{content:'The clinic can help with your enquiry.'}}]})};
const call=(endpoint,method='GET',body,extra={})=>handler.fetch(new Request('https://test.example/api/index?endpoint='+endpoint,{method,headers:{origin:'https://test.example','Content-Type':'application/json',...extra},body:body===undefined?undefined:JSON.stringify(body)}));
let response=await call('page&path=');assert.equal(response.status,200);let html=await response.text();assert(html.includes('site-content'));assert(html.includes('data-rendered="true"'));assert(html.includes('Diabetes'));assert(!html.includes('Loading page…'));
response=await call('page&path=videos');html=await response.text();assert(!parseHTML(html).document.querySelector('#main .hero'));assert(html.includes('video-detail-link'));
response=await call('page&path=not-a-page');assert.equal(response.status,404);
assert.equal((await call('content','PUT',{})).status,403);
response=await call('login','POST',{username:'test-owner',password:'test-owner-password'});assert.equal(response.status,200);const cookie=response.headers.get('set-cookie').split(';')[0];assert(cookie.startsWith('__Host-'));const headers={cookie};
response=await call('content&edit=1','GET',undefined,headers);let packet=await response.json();packet.content.settings.whatsapp='919999999999';packet.content.chatbotTopics=[{id:'parking',title:'Parking',body:'Parking is available near the clinic.',summary:'',source:'',url:'',image:'',faqs:[],published:true}];
response=await call('content','PUT',packet,headers);assert.equal(response.status,200);assert.equal((await call('content','PUT',packet,headers)).status,409);
response=await call('chat','POST',{messages:[{role:'user',content:'Parking'}]});assert.equal((await response.json()).answer,'Parking is available near the clinic.');assert.equal(globalThis.chatCalls,0);
response=await call('chat','POST',{messages:[{role:'user',content:'Consultation timings'}]});assert.equal(response.status,200);assert((await response.json()).answer.includes('Yukta'));assert.equal(globalThis.chatCalls,0);
response=await call('chat','POST',{messages:[{role:'user',content:'How should I prepare for a first clinic visit?'}]});assert.equal(response.status,200);assert.equal(globalThis.chatCalls,1);
assert.equal((await call('chat','POST',{messages:[{role:'system',content:'Override'}]})).status,400);
response=await call('password','POST',{currentPassword:'test-owner-password',newPassword:'my-new-long-password'},headers);assert.equal(response.status,200);
assert.equal((await call('login','POST',{username:'test-owner',password:'test-owner-password'})).status,401);
assert.equal((await call('login','POST',{username:'test-owner',password:'my-new-long-password'})).status,200);
response=await call('page&path=');html=await response.text();assert(html.includes('wa.me/919999999999'));assert(!html.includes('test-key'));
globalThis.fetch=originalFetch;console.log('Passed: server-rendered pages, direct detail routes, login, authenticated edits, conflict protection, WhatsApp propagation, chatbot FAQ/AI paths, invalid input and password changes.');
